# ----------------------------------------------------------
# app project generated by QMsNet (save function)
# ----------------------------------------------------------
TEMPLATE  = app
LANGUAGE  = C++

CONFIG	 += qt warn_on debug

OBJECTS_DIR = tmp\obj
MOC_DIR     = tmp\moc

HEADERS   =  \
	.\MyWidget.h
SOURCES   =  \
	main.cpp \
	.\MyWidget.cpp
IMAGES   =  \
    icons\icon_dock_left.png \
    icons\icon_dock_left_hi.png \
    icons\icon_dock_right.png \
    icons\icon_dock_right_hi.png \
    icons\icon_dock_top.png \
    icons\icon_dock_top_hi.png \
    icons\icon_dock_bottom.png \
    icons\icon_dock_bottom_hi.png \
    icons\icon_dock_tab.png \
    icons\icon_dock_tab_hi.png \
    icons\icon_dock_background.png \
    icons\icon_dock_background_hi.png \
    icons\icon_file_new.png
