***************
*** 68,79 ****
  # The compiler, C flags, preprocessor flags, etc
  
  CC = gcc
! CFLAGS =  -Wall -O3 -mms-bitfields -fms-extensions -fno-rtti -fno-exceptions -march=i386 
  CPPFLAGS =   -D__GTHREAD_HIDE_WIN32API -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64     
  CC_FOR_BUILD = $(CC)
  CFLAGS_FOR_BUILD = $(CFLAGS)
  CPPFLAGS_FOR_BUILD = @CPPFLAGS_FOR_BUILD@
! UTF8 = 
  NEWLINE = 
  POSIX_MALLOC_THRESHOLD = -DPOSIX_MALLOC_THRESHOLD=10
  LINK_SIZE = 
--- 68,80 ----
  # The compiler, C flags, preprocessor flags, etc
  
  CC = gcc
! CFLAGS =  -Wall -O3 -mms-bitfields -fms-extensions -fno-rtti -fno-exceptions -march=i386 \
!     -D__GTHREAD_HIDE_WIN32API -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64 
  CPPFLAGS =   -D__GTHREAD_HIDE_WIN32API -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64     
  CC_FOR_BUILD = $(CC)
  CFLAGS_FOR_BUILD = $(CFLAGS)
  CPPFLAGS_FOR_BUILD = @CPPFLAGS_FOR_BUILD@
! UTF8 = -DSUPPORT_UTF8
  NEWLINE = 
  POSIX_MALLOC_THRESHOLD = -DPOSIX_MALLOC_THRESHOLD=10
  LINK_SIZE = 
***************
*** 98,109 ****
  
  all:            libpcre.la  pcretest.exe pcregrep.exe  winshared
  
! pcregrep.exe: libpcre.la pcregrep.o  winshared
!         $(LINK) -o pcregrep.exe pcregrep.o -lpcre
  
! pcretest.exe: libpcre.la  pcretest.o  winshared
!         $(LINK) $(PURIFY) $(EFENCE) -o pcretest.exe  pcretest.o \
!         -lpcre 
  
  libpcre.la:     $(OBJ)
          -rm -f libpcre.la
--- 103,114 ----
  
  all:            libpcre.la  pcretest.exe pcregrep.exe  winshared
  
! pcregrep.exe: libpcre.la pcregrep.o pcregrep-rc.o  winshared
!         $(LINK) -o pcregrep.exe pcregrep.o pcregrep-rc.o -lpcre -lgw32c -lole32 -luuid
  
! pcretest.exe: libpcre.la  pcretest.o  pcretest-rc.o winshared
!         $(LINK) $(PURIFY) $(EFENCE) -o pcretest.exe  pcretest.o pcretest-rc.o \
!         -lpcre -lgw32c -lole32 -luuid
  
  libpcre.la:     $(OBJ)
          -rm -f libpcre.la
