//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WorldEditor.rc
//
#define IDCANCEL2                       3
#define IDCLEAR                         3
#define ID_WERM_HIDE_THIS               103
#define ID_WERM_SHOW_THIS               104
#define ID_LVRM_HIDE_THIS               105
#define ID_LVRM_SHOW_THIS               106
#define ID_CFM_ADD                      107
#define ID_CFM_FAVORITE_1               108
#define ID_CFM_FAVORITE_2               109
#define ID_CFM_FAVORITE_3               110
#define ID_CFM_FAVORITE_4               111
#define ID_CFM_FAVORITE_5               112
#define ID_CFM_FAVORITE_6               113
#define ID_CFM_FAVORITE_7               114
#define ID_CFM_FAVORITE_8               115
#define ID_CFM_FAVORITE_9               116
#define ID_CFM_FAVORITE_10              117
#define ID_CFM_MORE                     118
#define ID_LVRM_SELECTALL_THIS          119
#define ID_LVRM_SELECTALL_ANIM_THIS     120
#define ID_LVRM_SELECTALL_RIGID_THIS    121
#define ID_LVRM_HIDEALL_THIS            122
#define ID_LVRM_SHOWALL_THIS            123
#define ID_LVRM_THAW_THIS               124
#define ID_LVRM_FREEZE_THIS             125
#define ID_LVRM_THAWALL_THIS            126
#define ID_LVRM_FREEZEALL_THIS          127
#define ID_LVRM_HIDE_ALL                128
#define ID_LVRM_SHOW_ALL                129
#define ID_LVRM_THAW_ALL                130
#define ID_LVRM_FREEZE_ALL              131
#define ID_LVRM_SELECT_ALL              132
#define ID_LVRM_HIDE_ANIM_THIS          133
#define ID_LVRM_HIDE_RIGID_THIS         134
#define ID_LVRM_SHOW_ANIM_THIS          135
#define ID_LVRM_SHOW_RIGID_THIS         136
#define ID_LVRM_THAW_ANIM_THIS          137
#define ID_LVRM_THAW_RIGID_THIS         138
#define ID_LVRM_FREEZE_ANIM_THIS        139
#define ID_LVRM_FREEZE_RIGID_THIS       140
#define IDR_BLUEPRINT_BAR               600
#define IDR_AIVIEW_FILTER               604
#define IDD_RESOURCE_BROWSER_DLG        608
#define IDB_IMGLIST_TAB                 630
#define IDC_LB_REGISTERED_MGRS          643
#define IDC_AI_TREE_LIST                644
#define IDR_WORLDEDITOR                 645
#define IDC_BUTTON_RELOAD               646
#define IDC_BTN_CLEAR                   646
#define IDR_LAYER_LIST                  647
#define IDR_PALETTEVIEW_FILTER          648
#define IDR_OBJECT_LIST                 649
#define IDR_CREATE_OBJECT               650
#define IDR_LAYER_VIEW_BAR              651
#define IDB_LAYERLIST_ICONS             652
#define IDR_LEVEL_LIGHT_DIR             653
#define IDR_LEVEL_LIGHT_WHITE           654
#define IDR_LEVEL_LIGHT_DYNAMIC         655
#define IDR_LEVEL_LIGHT_ZONE            656
#define IDR_LEVEL_LIGHT_NORMAL          657
#define IDR_LEVEL_LIGHT_RAYCAST         658
#define IDR_LAYER_LOAD                  659
#define IDR_LAYER_UNLOAD                660
#define IDD_TRANSACTION_STACK_DIALOG    661
#define IDD_AUDIOPACKAGE_DIALOG         662
#define IDR_SOUNDVIEW_FILTER            663
#define IDC_TREE_OBJECTS                664
#define IDR_OBJECT_PALETTE              665
#define IDD_DIALOG_CONNECTION_ATTR      666
#define IDD_ANIMPACKAGE_DIALOG          667
#define IDR_GLOBALS_LIST                668
#define IDR_DEBUGGER_VIEW               669
#define IDR_GLOBAL_FILTER               670
#define IDD_NEW_GLOBAL_DLG              671
#define IDR_GUID_DEBUGGER               672
#define IDR_WATCH_LIST                  673
#define IDR_WATCHVIEW_FILTER            674
#define IDR_TRIGGER_VIEW_LIST           675
#define IDR_DECAL_PALETTE               682
#define IDR_TRIGGER_VIEW_BAR            684
#define IDD_CAMERA_FAVORITE_ADD         686
#define IDD_EDIT                        686
#define IDD_TEXT_ENTRY                  686
#define IDC_PREVIEW_FRAME               1700
#define IDC_TREE_RESOURCE_SELECTOR      1701
#define IDC_EDITOR_SETTINGS_GRIDSNAP    1702
#define IDC_EDITOR_SETTINGS_ROTATESNAP  1703
#define IDC_SOUND_TREE_LIST             1704
#define IDC_LIST_TRANSACTIONS           1705
#define IDC_AUDIOPKG_PACKAGE            1706
#define IDC_AUDIOPKG_DESC               1707
#define IDC_COMBO_CONNECTION_HINT_PATROL_ROUTE 1710
#define IDC_COMBO_CONNECTION_HINT_ONE_WAY 1711
#define IDC_COMBO_CONNECTION_HINT_DARK  1712
#define IDC_ANIMPKG_DESC                1713
#define IDC_COMBO_CONNECTION_HINT_SNEAKY 1714
#define IDC_GLOBAL_INT                  1714
#define IDC_COMBO_CONNECTION_HINT_COVER 1715
#define IDC_GLOBAL_FLOAT                1715
#define IDC_GLOBAL_BOOL                 1716
#define IDC_GLOBAL_TIMER                1717
#define IDC_GLOBAL_GUID                 1718
#define IDC_GLOBAL_NAME                 1719
#define IDC_EDIT1                       1720
#define IDC_NAME                        1720
#define IDC_BUTTON1                     1722
#define ID_WETB_SHOWGRID                32794
#define ID_WETB_SHOWSPACD               32797
#define ID_WETB_SHOWAXIS                32800
#define ID_PVTB_FILTER_WALL             32802
#define ID_PVTB_FILTER_FLOOR            32803
#define ID_PVTB_FILTER_CEILING          32804
#define ID_WETB_CREATE_OBJECT           32805
#define ID_WETB_DELETE_SELECTED         32806
#define ID_WETB_SNAPTOGRID              32809
#define ID_BPTB_CREATE_BLUEPRINT        32810
#define ID_BPTB_CREATE_OBJECT           32811
#define ID_BPTB_ADD_BLUEPRINT           32814
#define ID_WETB_MOVEMODE                32815
#define ID_BPTB_ADD_BLUEPRINT_AS_OBJECTS 32816
#define IDC_COMBOBOX_ACTIVE_LAYER       32817
#define ID_LVTB_NEW_LAYER               32819
#define ID_BUTTON_CREATE_NAV_NODE       32821
#define ID_BUTTON_CREATE_NAV_CONNECTION 32822
#define ID_BUTTON_CREATE_FORCED_NAV_ZONE 32823
#define ID_LVTB_DELETE_LAYER            32824
#define ID_LVTB_RENAME_LAYER            32825
#define ID_LVTB_SET_ACTIVE_LAYER        32826
#define ID_BUTTON32828                  32828
#define IDR_CREATE_OBJECT_FROM_SELECTED 32829
#define ID_WETB_ADDWITHRAY              32830
#define ID_LVTB_LIGHT_LAYER             32831
#define ID_BUTTON_SET1                  32832
#define ID_BUTTON_SET2                  32833
#define ID_BUTTON_GO                    32834
#define ID_BPTB_SHATTER_BLUEPRINT       32835
#define ID_WETB_SHOWSELECTIONBOUNDS     32836
#define ID_WETB_GRIDTOOBJECT            32837
#define ID_WETB_RUNGAME                 32838
#define ID_BUTTON_CREATE_PLAYER         32839
#define ID_WETB_TOGGLE_FPV              32840
#define ID_BPTB_CREATE_ANCHOR           32841
#define ID_LVTB_SELECT_LAYER            32843
#define ID_WETB_COPY_OBJECTS            32844
#define ID_WETB_MOVE_OBJECTS_TO_ACTIVE_LAYER 32845
#define ID_WETB_UNDO                    32846
#define ID_WETB_REDO                    32848
#define ID_CREATE_SOUNDNAV_NODE         32852
#define ID_CREATE_SOUNDNAV_CONNECTION   32853
#define ID_WETB_TRANS_STACK             32854
#define ID_BPTB_SHATTER_FOR_EDIT        32855
#define ID_WETB_FOCUS_CAMERA            32856
#define ID_LVTB_NEW_FOLDER              32857
#define ID_BUTTON32858                  32858
#define ID_LVTB_LOAD_LAYER              32859
#define ID_WETB_LIGHT_LEVEL             32862
#define ID_LVTB_LOAD_ALL_LAYERS         32864
#define ID_LVTB_NEW_RES                 32865
#define ID_WETB_RENDER_SPEC             32866
#define ID_WETB_PAUSEGAME               32867
#define ID_OVTB_ADD_PLAYSURFACE         32868
#define ID_OVTB_ADD_PROPSURFACE         32870
#define ID_OVTB_ADD_ANIMSURFACE         32871
#define ID_OVTB_REFRESH                 32872
#define ID_BPTB_REFRESH                 32873
#define ID_OVTB_UPDATE_GEOMS_FROM_SEL   32874
#define ID_LVTB_NEW_ZONE                32875
#define ID_LVTB_NEW_PORTAL              32876
#define ID_BUTTON_CHAIN_NODES           32877
#define ID_BUTTON_CONNECT_VISIBLE       32880
#define ID_BUTTON_CHECK_ALL_NODES       32881
#define ID_BUTTON_CONNECT_MODE          32882
#define ID_BUTTON_CONNECT_SELECTED      32885
#define ID_BUTTON_BATCH_FLAG            32886
#define ID_WETB_PORTAL_WALK             32887
#define ID_OVTB_UPDATE_RIGIDINST_FROM_SEL 32888
#define ID_WETB_SOUND_DEBUG_STATS       32890
#define ID_WETB_SOUND_PRINT_PACKAGE_DATA 32891
#define ID_WETB_SOUND_PROPAGATE         32892
#define ID_GVTB_NEW_FOLDER              32893
#define ID_GVTB_NEW_GLOBAL              32894
#define ID_GVTB_DELETE_GLOBAL           32895
#define ID_BUTTON32897                  32897
#define ID_GVTB_REFRESH                 32897
#define ID_WETB_REFRESH_RSC             32898
#define ID_GDTB_REVERSE_LOOKUP          32901
#define ID_GDTB_GUID_LOOKUP             32902
#define ID_GDTB_CLEAR_INFO              32903
#define ID_GDTB_GLOBAL_GUID_LOOKUP      32904
#define ID_LVTB_CHECKOUT_LAYER          32905
#define ID_RENDER_ICONS                 32906
#define ID_WETB_RENDER_ICONS            32907
#define ID_WETB_SAVEGAME                32908
#define ID_WETB_LOADGAME                32909
#define ID_WVTB_CLEAR_INFO              32910
#define ID_WVTB_WATCH_PROP              32911
#define ID_WVTB_WATCH_GLOBAL            32912
#define ID_WVTB_DELETE_WATCH            32913
#define ID_WETB_STEPGAME                32914
#define TB_PAINT_MODE                   32915
#define TB_SELECT_MODE                  32916
#define ID_DPTB_REFRESH                 32917
#define ID_DVTB_REFRESH                 32918
#define ID_DVTB_PAINT_MODE              32920
#define ID_DVTB_SELECT_MODE             32921
#define ID_TRTB_REFRESH                 32922
#define ID_WETB_CAMERA_HISTORY_PREV     32923
#define ID_WETB_CAMERA_HISTORY_NEXT     32924
#define ID_WETB_CAMERA_FAVORITES        32925
#define ID_WETB_GOTO_PLAYER             32926
#define ID_OVTB_SELECT_BASED_ON_RIGID   32927
#define ID_BPTB_REPLACE_SELECTED_WITH_BLUEPRINT 32930
#define ID_BPTB_RESYNC                  32931
#define ID_BUTTON32932                  32932
#define IDR_CREATE_OBJECT_GENERIC_FIRST 34901
#define IDR_CREATE_OBJECT_GENERIC_LAST  34999
#define IDW_WORKSPBAR                   59402
#define IDW_PROPERTY_BAR                59403
#define IDW_PALETTE_BAR                 59404

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        687
#define _APS_NEXT_COMMAND_VALUE         32933
#define _APS_NEXT_CONTROL_VALUE         1723
#define _APS_NEXT_SYMED_VALUE           119
#endif
#endif
