//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PartEd.rc
//
#define IDOK2                           3
#define IDD_ABOUTBOX                    100
#define IDC_PROP_GRID_ITEM              101
#define IDR_MAINFRAME                   102
#define IDR_PARTEDTYPE                  103
#define IDC_SELECT                      138
#define IDC_3D_CREATE                   140
#define IDR_TOOLBAR3D                   145
#define IDR_MENU_VIEW3D                 147
#define IDB_VIEWPORT_MAXIMIZE_COLOR     148
#define IDB_VIEWPORT_MAXIMIZE_ALPHA     149
#define IDR_MAIN_TOOLBAR                159
#define IDD_ELEM_LIST                   161
#define IDD_ERRORDIALOG                 162
#define IDB_UP                          163
#define IDD_AVI_EXPORT                  165
#define IDB_DOTCOM                      167
#define IDB_VCR                         501
#define IDB_VCR_COLOR                   502
#define IDB_VCR_HOME_COLOR              503
#define IDB_VCR_HOME_ALPHA              504
#define IDB_VCR_END_COLOR               505
#define IDB_VCR_LOOPOFF_COLOR           506
#define IDB_VCR_LOOPON_COLOR            507
#define IDB_VCR_PAUSE_COLOR             508
#define IDB_VCR_PLAY_COLOR              509
#define IDB_VCR_STEPBACK_COLOR          510
#define IDB_VCR_STEPFORWARD_COLOR       511
#define IDB_VCR_END_ALPHA               512
#define IDB_VCR_LOOPOFF_ALPHA           513
#define IDB_VCR_LOOPON_ALPHA            514
#define IDB_VCR_PAUSE_ALPHA             515
#define IDB_VCR_PLAY_ALPHA              516
#define IDB_VCR_STEPBACK_ALPHA          517
#define IDB_VCR_STEPFORWARD_ALPHA       518
#define IDB_VCR_KEYSTEP_COLOR           519
#define IDB_VCR_KEYSTEP_ALPHA           520
#define IDB_VCR_ALPHA                   521
#define IDC_MOVE                        521
#define IDB_DOWN                        521
#define IDC_ROTATE                      523
#define IDC_SCALE                       524
#define IDC_PAN                         525
#define IDC_VCR_FILTER                  526
#define IDC_VCR_ANIMATE                 527
#define IDC_VCR_HOME                    528
#define IDC_VCR_STEPBACK                529
#define IDC_VCR_PLAY                    530
#define IDC_VCR_STEPFORWARD             531
#define IDC_VCR_END                     532
#define IDC_VCR_REPEAT                  533
#define IDC_VCR_KEYSTEP                 534
#define IDC_KEYBAR_EDIT_FRAMESTART      535
#define IDC_KEYBAR_EDIT_FRAMEEND        536
#define IDC_KEYBAR_EDIT_FRAMECURRENT    537
#define IDC_KEYBAR_TIMESLIDER           538
#define IDC_KEYBAR_STATUSLEFT           539
#define IDC_KEYBAR_STATUSRIGHT          540
#define IDC_VIEWPORT_MAXIMIZE           1000
#define IDC_VIEWPORT_CAMERA_LIST        1001
#define IDC_VIEWPORT_SHADING_MENU       1002
#define IDC_VIEWPORT_DISPLAY_MENU       1003
#define IDC_VIEWPORT_NAVIGATE_MENU      1004
#define IDC_VIEWPORT_CAMERA_BOOKMARK1   1005
#define IDC_VIEWPORT_CAMERA_BOOKMARK2   1006
#define IDC_VIEWPORT_CAMERA_BOOKMARK3   1007
#define IDC_VIEWPORT_CAMERA_BOOKMARK4   1008
#define IDC_ELEM_LIST                   1009
#define IDC_RENAME_SELECTED             1010
#define IDC_EDIT                        1013
#define IDC_DOWN                        1014
#define IDC_UP                          1015
#define IDC_FILENAME                    1017
#define IDC_BROWSE_AVI                  1018
#define IDC_VIEW_SEL                    1019
#define IDC_OUTPUT_RES                  1020
#define IDC_START_FRAME                 1021
#define IDC_END_FRAME                   1022
#define IDC_HIDE                        1022
#define IDC_FX_VER                      1023
#define ID_CREATE_SPRITE                30000
#define ID_CREATE_SPRITEEMITTER         30001
#define ID_CREATE_SPEMITTER             30001
#define ID_CREATE_LIGHT                 30002
#define ID_CREATE_MESH                  30003
#define ID_FILE_EXPORT                  30004
#define ID_VIEW_BUTTON1                 30008
#define ID_VIEW_BUTTON2                 30009
#define ID_VIEW_4WAY                    30012
#define ID_MAIN_TOOLBAR_UNDO            30014
#define ID_MAIN_TOOLBAR_REDO            30015
#define ID_MAIN_TOOLBAR_SELECT          30016
#define ID_MAIN_TOOLBAR_MOVE            30017
#define ID_MAIN_TOOLBAR_ROTATE          30018
#define ID_MAIN_TOOLBAR_SCALE           30019
#define ID_MAIN_TOOLBAR_AXIS_X          30020
#define ID_MAIN_TOOLBAR_AXIS_Y          30021
#define ID_MAIN_TOOLBAR_AXIS_Z          30022
#define ID_MAIN_TOOLBAR_ALIGN           30023
#define ID_EDIT_SELECT_NONE             30024
#define ID_EDIT_SELECT_INVERT           30025
#define ID_EDIT_SELECT_BYNAME           30026
#define ID_VIEW_VIEWPORT_GRIDS          30027
#define ID_VIEW_MAXIMIZE_VIEWPORT       30028
#define ID_VIEW_VIEWPORT_MAXIMIZE       30029
#define ID_EDIT_CLONE                   30030
#define ID_VIEW_BBOX                    30031
#define ID_FILE_EXPORTVIDEOAVI          30032
#define ID_EDIT_MOVETO_000              30033
#define ID_VIEW_TRAJECTORY              30034
#define ID_VIEW_VELOCITY                30035
#define ID_VIEW_REDRAW_ALL              30036
#define ID_CREATE_PLANE                 30037
#define ID_CREATE_SHOCKWAVE             30038
#define ID_CREATE_SPHERE                30039
#define ID_CREATE_CYLINDER              30040
#define ID_CREATE_RIBBON                30041
#define ID_VIEW_HIDE_SELECTED           30042
#define ID_VIEW_UNHIDE_ALL              30043
#define ID_TIME_GOTO_FIRST_FRAME        30044
#define ID_TIME_GOTO_LAST_FRAME         30045
#define ID_TIME_GOTO_PREVIOUS_FRAME     30046
#define ID_TIME_GOTO_NEXT_FRAME         30047
#define ID_TIME_PLAY                    30048
#define ID_TIME_ZOOM_TIME_EXTENTS       30049
#define IDW_KEYBAR                      59400
#define IDW_PROPERTIES                  59401
#define IDW_VIEWPORT_TOOLBAR            59402

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         30050
#define _APS_NEXT_CONTROL_VALUE         1024
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
